### ISSUE TITLE
Image Fix

### ISSUE THREAD

**Issue by AlexHedley** [AlexHedley/blog#6]
```css
img {
    max-width: 80%;
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

Can I add `/input/styles/site.css`?

https://wyam.io/recipes/blog/themes/cleanblog

- `/assets/css/override.css`

> You can use this file to define additional CSS styles. You can also define CSS override styles in this file since it's included after the main Bootstrap and theme CSS files.
